import './runtime-config'

export type { FontConfig, TypographyConfig } from './typography'
export type { ScrollbarConfig } from './scrollbar'
export type { CursorConfig } from './cursor'
export type { ThemeColors, ThemeTranslations, ColorsConfig, ThemeIconFormats } from './colors'
export type { ThemeConfig } from './theme'
export type { TranslationConfig } from './translation'
export type { ColorOptions } from './color-options'
export type { UnoCSSOptions } from './unocss'
export type { VuetifyOptions } from './vuetify'
export type { IconOptions } from './icon'
